class InbuiltQuotes {
  static const List<String> quotes = [
    "Procrastination is the bad habit of putting off until the day after tomorrow what should have been done the day before yesterday.",
    "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.",
    "Great achievement is usually born of great sacrifice, and is never the result of selfishness.",
    "The starting point of all achievement is desire.",
    "Some people dream of success, while others wake up and work hard at it.",
    "When your desires are strong enough, you will appear to possess superhuman powers to achieve.",
    "Patience, persistence and perspiration make an unbeatable combination for success.",
    "Fall down, get up, fall down, get up, fall down, get up, fall down, get up, fall down, get up, fall down, get up, fall down, get up, stay up, help others.",
    "You will be 1 in a million, literally.",
    "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.",
    "We gain the strength of the temptation we resist.",
    "Do it for the people who want to see you fail",
    "The temptation to quit will be greatest just before you are about to succeed.",
    "“I don’t jerk off”, feels real good to say.",
    "“Winning doesn’t always mean being first. Winning means you’re doing better than you’ve done before.”",
    "When there is no enemy within, the enemies outside can do you no harm.",
    "You didn’t come this far, to only come this far.",
    "An addict who overcomes addiction is capable of accomplishing anything.",
    "One day or day one, you decide.",
    "“The secret of change is to focus all of your energy not on fighting the old, but on building the new.”",
    "A mistake repeated more than once is a decision",
    "If you are tired of starting over, stop giving up",
    "“The struggle you’re in today is developing the strength you need tomorrow.”",
    "Change the world by being yourself.",
    "Aspire to inspire before we expire",
    "Everything you can imagine is real.",
    "Simplicity is the ultimate sophistication.",
    "What we think, we become.",
    "All limitations are self-imposed. ",
    "Tough times never last but tough people do.",
    "Problems are not stop signs, they are guidelines.",
    "Hate comes from intimidation, love comes from appreciation.",
    "Oh, the things you can find, if you don’t stay behind.",
    "Determine your priorities and focus on them.",
    "Be so good they can’t ignore you.",
    "Dream as if you’ll live forever, live as if you’ll die today.",
    "I don’t need it to be easy, I need it to be worth it.",
    "Never let your emotions overpower your intelligence.",
    "Don’t you know your imperfections is a blessing?",
    "Reality is wrong, dreams are for real. ",
    "To live will be an awfully big adventure. ",
    "There is no substitute for hard work.",
    "What consumes your mind controls your life",
    "Strive for greatness. ",
    "Wanting to be someone else is a waste of who you are. ",
    "And still, I rise.",
    "The time is always right to do what is right.",
    "Let the beauty of what you love be what you do. ",
    "May your choices reflect your hopes, not your fears.",
    "A happy soul is the best shield for a cruel world.",
    "White is not always light and black is not always dark. ",
    "Life becomes easier when you learn to accept the apology you never got.",
    "Turn your wounds into wisdom. ",
    "Happiness depends upon ourselves.",
    "Change the game, don’t let the game change you.",
    "If the world was blind how many people would you impress?",
    "The meaning of life is to give life meaning",
    "Some people don't like change, but you need to embrace change if the alternative is disaster.",
    "Persistence is very important. You should not give up unless you are forced to give up.",
    "If you get up in the morning and think the future is going to be better, it is a bright day. Otherwise, it's not.",
    "You only live once, but if you do it right, once is enough.",
    "Many of life’s failures are people who did not realize how close they were to success when they gave up",
    "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.",
    "The unexamined life is not worth living.",
    "Turn your wounds into wisdom.",
    "Do all the good you can, for all the people you can, in all the ways you can, as long as you can",
    "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this",
    "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this",
    "Life is really simple, but men insist on making it complicated.",
    "Life is like a coin. You can spend it any way you wish, but you only spend it once",
    "Keep calm and carry on.",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
    "Every strike brings me closer to the next home run.",
    "When we strive to become better than we are, everything around us becomes better too.",
    "If we don’t change, we don’t grow. If we don’t grow, we aren’t really living",
  ];
}
